# Generated by Django 4.1.3 on 2023-11-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_importinvoicedetail_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinvoicedetail',
            name='import_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.importproduct'),
        ),
    ]
