# Generated by Django 4.1.3 on 2023-11-20 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0007_remove_exportinvoicedetail_export_product_and_more'),
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('dealer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='ImportInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('dealer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='ImportInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.importproduct')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='invoice.importinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='ExportInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.exportproduct')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.exportinvoice')),
            ],
        ),
    ]
